FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
ENV NODE_ENV=production
RUN npm run build

EXPOSE 3000

# Run production server
CMD ["npm", "run", "start"]

